INSERT INTO USER (ID, USER_ID, PASSWORD, NAME, EMAIL, CREATE_DATE) VALUES (1, 'ben', 'ben', 'ben', 'ben@gmail.com', CURRENT_TIMESTAMP());
INSERT INTO USER (ID, USER_ID, PASSWORD, NAME, EMAIL, CREATE_DATE) VALUES (2, 'summer', 'summer', 'summer', 'summer@gmail.com', CURRENT_TIMESTAMP());

INSERT INTO QUESTION (ID, FK_QUESTION_WRITER, TITLE, CONTENTS, CREATE_DATE, COUNT_OF_ANSWER) VALUES (1, 1, 'BEN이 작성한 글' ,'HELLO WORLD', CURRENT_TIMESTAMP(), 0);

